version: '3.8'

services:
  postgres:
    image: debezium/postgres:14-alpine
    container_name: postgres_v_1
    environment:
      POSTGRES_DB: v_1
      POSTGRES_PASSWORD: ${POSTGRES_V_1_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.1-alpine
    container_name: redis_v_1
    ports:
      - "6379:6379"
  meilisearch:
    image: getmeili/meilisearch:v1.3
    container_name: meilisearch_v_1
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_V_1_MASTER_KEY}
    volumes:
      - ./meili_data:/meili_data
  # django:
  #   depends_on:
  #     - meilisearch
  #     - postgres
  #     - redis
  # go
  #   depends_on:
  #     - meilisearch
  meilisync:
    image: long2ice/meilisync
    volumes:
      - ./meilisync_config.yml:/meilisync/config.yml
    restart: always
    depends_on:
      - postgres
      - meilisearch