version: '3.8'

services:
  postgres:
    image: debezium/postgres:14-alpine
    container_name: postgres_v_1_main
    environment:
      POSTGRES_DB: v_1
      POSTGRES_PASSWORD: ${POSTGRES_V_1_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  # redis:
  #   image: redis:7.2.1-alpine
  #   container_name: redis_v_1
  #   ports:
  #     - "6379:6379"
  meilisearch:
    image: getmeili/meilisearch:v1.3
    container_name: meilisearch_v_1_main
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_V_1_MASTER_KEY}
    volumes:
      - ./meili_data:/meili_data
  # django:
  #   build:
  #     context: ./V-Django-Backend
  #     dockerfile: ./V-Django-Backend/compose/local/django/Dockerfile
  #   container_name: django_v_1
  #   command: bash /start
  #   volumes:
  #     - ./V-Django-Backend:/app
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #     - redis
  #     - meilisearch
  # go
  #   depends_on:
  #     - meilisearch
