debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: postgres
  host: postgres
  port: 5432
  user: postgres
  password: ${POSTGRES_V_1_PASSWORD}
  database: v_1
meilisearch:
  api_url: meilisearch
  api_key: ${MEILISEARCH_V_1_MASTER_KEY}
  insert_size: 1000
  insert_interval: 10
sync:
  - table: speeds_speed
    index: speeds
    plugins:
      - meilisync.plugin.Plugin
sentry:
  dsn: ""
  environment: "production"